server.port=8081
spring.data.mongodb.uri=mongodb+srv://smartcampus_admin:pceQynoeTQpkoSUq@cluster0.okcq0yk.mongodb.net/
spring.application.name=backend
spring.data.mongodb.host=
spring.data.mongodb.port=