server.port=8081
spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://admin:admin@cluster0.bwo0he7.mongodb.net/DB?retryWrites=true&w=majority&appName=Cluster0
spring.jackson.time-zone=Asia/Colombo
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.smartcampus=DEBUG